#undef MyPVNodeSMP
#undef OppPVNodeSMP
#undef MyAllSMP
#undef OppAllSMP
#undef MyCutSMP
#undef OppCutSMP

#undef MyMultiPV

#undef MyPVQsearch
#undef MyPVQsearchCheck
#undef MyQsearch
#undef MyQsearchCheck
#undef MyLowDepth
#undef MyLowDepthCheck
#undef MyExclude
#undef MyExcludeCheck
#undef MyCut
#undef MyCutCheck
#undef MyAll
#undef MyAllCheck
#undef MyPV
#undef MyRootNode
#undef MyRootNodeMonteCarlo
#undef MyAnalysis
#undef MyTop
#undef MyTopNodeMonteCarlo
#undef MyTopAnalysis
#undef MyAttacked
#undef OppAttacked
#undef MyAttackedPawns
#undef OppAttackedPawns
#undef OppPVQsearch
#undef OppPVQsearchCheck
#undef OppQsearch
#undef OppQsearchCheck
#undef OppLowDepth
#undef OppLowDepthCheck
#undef OppExclude
#undef OppExcludeCheck
#undef OppCut
#undef OppCutCheck
#undef OppAll
#undef OppAllCheck
#undef OppPV
#undef OppRootNode
#undef OppAnalysis
#undef OppTop
#undef OppTopAnalysis
#undef OppOccupied
#undef BitboardOppP
#undef BitboardOppN
#undef BitboardOppBL
#undef BitboardOppBD
#undef BitboardOppR
#undef BitboardOppQ
#undef BitboardOppK
#undef MyOccupied
#undef BitboardMyP
#undef BitboardMyN
#undef BitboardMyBL
#undef BitboardMyBD
#undef BitboardMyR
#undef BitboardMyQ
#undef BitboardMyK
#undef MyKingSq
#undef OppKingSq
#undef EnumOppP
#undef EnumOppN
#undef EnumOppBL
#undef EnumOppBD
#undef EnumOppR
#undef EnumOppQ
#undef EnumOppK
#undef EnumMyP
#undef EnumMyN
#undef EnumMyBL
#undef EnumMyBD
#undef EnumMyR
#undef EnumMyQ
#undef EnumMyK
#undef OppKingCheck
#undef MyCapture
#undef MyOrdinary
#undef MyPositionalGain
#undef MyEvasion
#undef MyQuietChecks
#undef MySEE
#undef MAKE
#undef UNDO
#undef ILLEGAL_MOVE
#undef MOVE_IS_CHECK
#undef MyOK
#undef MyNext
#undef MyNull
#undef HasPiece
#undef SIXTH_RANK
#undef FOURTH_RANK
#undef FOURTH_RANK_BITBOARD
#undef IsPassedPawn
#undef MyXRAY
#undef OppXRAY
#undef MyXrayTable
#undef OppXrayTable
#undef MyKingCheck
#undef MY_COUNT
#undef MY_COUNT_FLEE
#undef IN_CHECK
#undef OppKdanger

#undef EIGHTH_RANK
#undef CAPTURE_RIGHT
#undef FROM_LEFT
#undef CAPTURE_LEFT
#undef FROM_RIGHT
#undef FORWARD
#undef FORWARD_LEFT
#undef FORWARD_RIGHT
#undef BACKWARD
#undef FORWARD_SHIFT
#undef BACK_SHIFT
#undef SEVENTH_RANK
#undef BACK_SHIFT2
#undef FORWARD2
#undef SECOND_RANK
#undef SECOND_SIXTH_RANKS
#undef ON_THIRD_RANK
#undef SECOND_SIXTH_RANKS
#undef BITBOARD_SEVENTH_RANK
#undef BITBOARD_EIGHTH_RANK
#undef WHITE_A7
#undef WHITE_H7

#undef CaptureEP
#undef PromQueenCap
#undef PromKnightCap

#undef CastleOO
#undef CastleOOO
#undef WHITE_F1G1
#undef WHITE_C1D1
#undef WHITE_B1C1D1
#undef WHITE_E1
#undef WHITE_C1
#undef WHITE_G1
#undef UnderProm

#undef ON_SECOND_RANK
#undef CAN_CAPTURE_RIGHT
#undef CAN_CAPTURE_LEFT
#undef PAWN_GUARD
#undef FOURTH_EIGHTH_RANK_NOh
#undef FOURTH_EIGHTH_RANK_NOa
#undef BACK_RIGHT
#undef BACK_RIGHT2
#undef BACK_RIGHT3
#undef BACK_LEFT
#undef BACK_LEFT2
#undef BACK_LEFT3
#undef NUMBER_RANK5

#undef NUMBER_RANK1
#undef NUMBER_RANK2
#undef NUMBER_RANK7
#undef PIECE_IS_MINE
#undef PIECE_IS_OPP
#undef BACKWARD2

#undef PIECE_IS_OPP_PAWN
